[project]
name = "siptasummerschoolproblychallenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "probly>=0.9.1",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "ruff>=0.16.1",
    "ty>=0.0.65",
]
